---
title: "Main"
author: "Yuki Matsuura"
date: "2024-06-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(here)
library(rio)
library(stargazer)
library(fixest)
library(haven)
library(interplot)
library(tidyfit)
library(lmtest)
library(sandwich)
library(countrycode)
```

```{r}
## Load data set
msf <- read_csv("data/MSFS-estimates_full-3x2000.csv") # Solis & Waggoner (2021)
gmfd <- read_csv("data/GMFD_V2.csv") # Whitten-Woodring & Van Belle (2017)
colpus <- read_dta("data/Master_Coup List_all regimes_basic.dta") # Chin et al. (2021)
powell <- read_dta("data/determinants_replication.dta") # Powell (2012), for covariates
coup <- read.table(file = "data/powell_thyne_ccode_year.txt",
                   header = TRUE,
                   sep = "\t") # Powell & Thyne (2011)
```

```{r}
## Merging data sets
df_coup <- left_join(x = coup, 
                     y = msf, 
                     by = c("ccode", "year")) %>% 
  left_join(y = powell, by = c("ccode", "year")) %>% 
  mutate(coup = ifelse(coup1 >= 1, 1, 0)) %>% 
  mutate(postcw = ifelse(year >= 1990, 1, 0))
```


```{r}
## Mass protest from Vdem data
library(vdemdata)
df_vdem <- vdem %>% 
  filter(year >= 1945) %>% 
  mutate(ccode = countrycode(sourcevar = country_name,
                             origin = "country.name",
                             destination = "cown")) %>% 
  dplyr::select(country_name, ccode, year, v2casoe_5)
df_coup <- left_join(x = df_coup,
                     y = df_vdem,
                     by = c("ccode", "year"))
```

## Analysis
## Bivariate analysis
```{r}
reg1 <- feglm(fml = coup ~ MSF,
             data = df_coup,
             family = binomial("logit"),
             cluster = c("ccode", "year"))
summary(reg1)
etable(reg1, se = "twoway", cluster = c("ccode", "year"))
esttex(reg1,
       title = "Bivariate analysis",
       label = "tab:bivariate")
```


```{r}
## fixest
formula <- formula(coup ~ MSF + postcw + MSF:postcw + soquall + lmilper + 
                     chgdp + lgdppcl + dem + auth + instab)
reg2 <- feglm(fml = formula, 
             data = df_coup, 
             family = binomial(link = "logit"),
             cluster = c("ccode", "year"))
summary(reg2)
etable(reg1, reg2)

## Logit
formula_fe <- formula(coup ~ MSF + postcw + MSF:postcw + soquall + lmilper + 
                        chgdp + lgdppcl + dem + auth + instab +
                        factor(ccode) + factor(year))
reg <- glm(formula = formula_fe, 
           data = df_coup, 
           family = binomial(link = "logit"))
summary(reg)
stargazer(reg, type = "text")
```

```{r}
## Interaction plot
interplot(m = reg, var1 = "MSF", var2 = "postcw") +
  labs(x = "Post cold war dummy", 
       y = "Media Freedom", 
       title = "Interaction plot") %>% 
  print()
```

```{r}
## 

## fixest (milreg maybe the key?)
formula <- formula(coup ~ MSF + postcw + MSF:postcw + chgdp + lgdppcl +
                     dem + auth + milreg + instab)
reg <- feglm(fml = formula,
             data = df_coup,
             family = binomial(link = "logit"),
             cluster = c("ccode", "year"))
summary(reg)
etable(reg)

## Logit
formula_fe <- formula(coup ~ MSF + postcw + MSF:postcw + chgdp + lgdppcl +
                        dem + auth + instab +
                        factor(year) + factor(ccode))
reg <- glm(formula = formula_fe,
           data = df_coup,
           family = binomial(link = "logit"))
summary(reg)
stargazer(reg, type = "text")
```

```{r}
## Only colpus countries (only significant with logit model)
df_coup_colpus <- df_coup %>% 
  filter(ccode %in% unique(colpus$ccode)) %>% 
  filter(!is.na(MSF)) %>% 
  filter(postcw == 1)

## fixest
formula <- formula(coup ~ MSF + soquall + lmilper + 
                     lgdppcl + dem + auth + instab)
reg <- feglm(fml = formula,
             data = df_coup_colpus,
             family = binomial(link = "logit"),
             cluster = c("ccode", "year"))
summary(reg)
etable(reg)

## Logit
formula_fe <- formula(coup ~ MSF +soquall + lmilper + lgdppcl +
                        dem + auth + instab +
                        factor(ccode) + factor(year))
reg <- glm(formula = formula_fe,
           data = df_coup_colpus,
           family = binomial(link = "logit"))
summary(reg)
stargazer(reg, type = "text")
```

```{r}
## Linear probability model
reg <- lm(formula = coup ~ MSF + postcw + MSF:postcw + soquall + lmilper + 
            lgdppcl + dem + auth + instab+ factor(ccode) + factor(year), 
          data = df_coup)
summary(reg)

ggplot(data = df_coup,
       mapping = aes(x = MSF, y = coup)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

data.frame(pred = reg$fitted.values, 
           res2 = reg$residuals^2) %>%
  ggplot(.,
         mapping = aes(x = pred, y = res2)) +
  geom_point()

vv <- vcovHC(reg, type = "HC1")
coeftest(reg, vcov = vv)
```

```{r}
## Rolling window analysis
mod_frame <- df_coup %>% 
  group_by(ccode) %>% 
  regress(formula = coup ~ MSF + postcw + MSF:postcw + soquall + lmilper + 
             lgdppcl + dem + auth + instab,
          m("glm", family = binomial(link = "logit")))
```
